v5 (#118)
* Clean up for v5

* Update version constraint

* Adjust grace period

* Remove old log_integration var

* Fix environment variables

* Upgrade notes

* Refactor secrets

* Refactor and more clean up

* Adjust internal names

* Adjust docs and improve external secret reliability

* Remove unnecessary sidecar_ prefix

* Adjust variable names and description

* Validation rules and format

* Fix issue with BYOS

* Linting code

* Remove support for gcr.io

* Update upgrade notes

* Update upgrade notes

* Update upgrade notes

diff --git a/files/cloud-init-functions.sh.tmpl b/files/cloud-init-functions.sh.tmpl
--- a/files/cloud-init-functions.sh.tmpl
+++ b/files/cloud-init-functions.sh.tmpl
@@ -4,13 +4,6 @@ function package_install(){
     yum install -y aws-cfn-bootstrap wget ec2-instance-connect docker jq
 }
 
-function docker_compose_install(){
-    # Compose Setup
-    sudo mkdir -p /usr/local/lib/docker/cli-plugins/
-    sudo ${curl} -SsfL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
-    sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
-}
-
 function docker_setup(){
     echo "Configuring Docker..."
     sudo usermod -a -G docker ec2-user
@@ -84,9 +77,8 @@ function get_secret_value() {
 
 function get_secret(){
     echo "Fetching Secret..."
-    if ! secret=$(aws secretsmanager get-secret-value --secret-id "${secrets_location}" --query SecretString --output text --region "${aws_region}" 2>&1); then
-        echo "Unable to fetch secret ${secrets_location}"
-        echo "Error: $secret"
+    if ! secret=$(get_secret_value "${secret_arn}" "${secret_role_arn}"); then
+        echo "ERROR: Unable to fetch sidecar secrets from ${secret_arn} see error above"
         exit 1
     fi
     SIDECAR_CLIENT_ID=$(echo "$secret" | jq -r .clientId)
@@ -95,23 +87,24 @@ function get_secret(){
 
 function load_certs() {
     echo "Loading certificates..."
-    local sidecar_tls_cert_secret_value sidecar_ca_cert_secret_value
-    if ! sidecar_tls_cert_secret_value=$(get_secret_value "${sidecar_tls_certificate_secret_arn}" "${sidecar_tls_certificate_role_arn}"); then
-        echo "WARNING: Unable to fetch shared TLS certificate from ${sidecar_tls_certificate_secret_arn} see error above"
+    local tls_cert_secret_value ca_cert_secret_value
+    if ! tls_cert_secret_value=$(get_secret_value "${tls_certificate_secret_arn}" "${tls_certificate_role_arn}"); then
+        echo "WARNING: Unable to fetch shared TLS certificate from ${tls_certificate_secret_arn} see error above"
     fi
-    if ! sidecar_ca_cert_secret_value=$(get_secret_value "${sidecar_ca_certificate_secret_arn}" "${sidecar_ca_certificate_role_arn}"); then
-        echo "WARNING: Unable to fetch shared CA certificate from ${sidecar_ca_certificate_secret_arn}" see error above.
+    if ! ca_cert_secret_value=$(get_secret_value "${ca_certificate_secret_arn}" "${ca_certificate_role_arn}"); then
+        echo "WARNING: Unable to fetch shared CA certificate from ${ca_certificate_secret_arn}" see error above.
     fi
-    SIDECAR_TLS_KEY=$(echo "$sidecar_tls_cert_secret_value" | extract_key_from_json_input)
-    SIDECAR_TLS_CERT=$(echo "$sidecar_tls_cert_secret_value" | extract_cert_from_json_input)
-    SIDECAR_CA_KEY=$(echo "$sidecar_ca_cert_secret_value" | extract_key_from_json_input)
-    SIDECAR_CA_CERT=$(echo "$sidecar_ca_cert_secret_value" | extract_cert_from_json_input)
+    SIDECAR_TLS_KEY=$(echo "$tls_cert_secret_value" | extract_key_from_json_input)
+    SIDECAR_TLS_CERT=$(echo "$tls_cert_secret_value" | extract_cert_from_json_input)
+    SIDECAR_CA_KEY=$(echo "$ca_cert_secret_value" | extract_key_from_json_input)
+    SIDECAR_CA_CERT=$(echo "$ca_cert_secret_value" | extract_cert_from_json_input)
 }
 
 function load_idp_certs() {
     echo "Loading IDP certificates..."
-    SIDECAR_IDP_PUBLIC_CERT="$(echo "$secret" | jq -r .sidecarPublicIdpCertificate)"
-    SIDECAR_IDP_PRIVATE_KEY="$(echo "$secret" | jq -r .sidecarPrivateIdpKey)"
+    IDP_CERTIFICATE=$(echo "$secret" | jq -r 'select(.idpCertificate != null) | .idpCertificate')
+    SIDECAR_IDP_PUBLIC_CERT=$(echo "$secret" | jq -r 'select(.sidecarPublicIdpCertificate != null) | .sidecarPublicIdpCertificate')
+    SIDECAR_IDP_PRIVATE_KEY=$(echo "$secret" | jq -r 'select(.sidecarPrivateIdpKey != null) | .sidecarPrivateIdpKey')
 }
 
 function fetch_hostname() {
@@ -156,39 +149,12 @@ function get_sidecar_version () {
     SIDECAR_VERSION=$(echo "$resp" | jq -r '.sidecar.version // empty')
 }
 
-function download_sidecar () {
-    local access_token url
-    echo "Downloading Sidecar Compose File..."
-    get_token "443"
-    if [[ $token_error -ne 0 ]]; then
-        error_443="$token"
-        get_token "8000"
-        if [[ $token_error -ne 0 ]]; then
-            echo "Unable to retrieve token!!"
-            echo "Attempt on 443: $error_443"
-            echo "Attempt on 8000: $token"
-            return 1
-        fi
-    fi
-    access_token=$(echo "$token" | jq -r .access_token)
-    url="https://${controlplane_host}/deploy/docker-compose?TemplateType=terraform&LogIntegration=${log_integration}&MetricsIntegration=${metrics_integration}&HCVaultIntegrationID=${hc_vault_integration_id}&WiresEnabled=${repositories_supported}&TemplateVersion=$SIDECAR_VERSION"
-    echo "Trying to download the sidecar template from: $url"
-    if ! ${curl} -fsS --no-progress-meter -o /home/ec2-user/sidecar.compose.yaml -L "$url" -H "Authorization: Bearer $access_token"; then
-        echo "Unable to download compose file for version $SIDECAR_VERSION, please make sure all parameters are correct"
-        return 1
-    fi
-    return 0
-}
-
 function registry_login () {
     echo "Container Registry Login..."
     local key=$(echo "$secret" | jq -r 'select(.containerRegistryKey != null) | .containerRegistryKey' | base64 --decode)
     if [[ ${container_registry} == *"aws"* ]]; then
         echo "(login): Logging in to AWS ECR..."
         eval $(aws ecr --no-include-email get-login  --region ${aws_region})
-    elif [ -n "$key" ]; then
-        echo "(login): Logging in to GCR..."
-        echo "$key" | docker login -u ${container_registry_username} --password-stdin https://gcr.io
     else
         echo "(login): Won't log in automatically to any image registry. Image registry set to: ${container_registry}"
     fi
@@ -211,15 +177,10 @@ function containerCheck () {
 function launch () {
     echo "Starting sidecar..."
     cd /home/ec2-user
-    if [[ ${use_single_container} == "true" ]]; then
-        SINGLE_CONTAINER_IMAGE=${container_registry}/cyral-sidecar:$SIDECAR_VERSION
-        retry docker pull -q $SINGLE_CONTAINER_IMAGE
-        retry docker run -d --name sidecar --network=host --log-driver=local --log-opt max-size=500m --restart=unless-stopped --env-file .env $SINGLE_CONTAINER_IMAGE
-        if ! containerCheck "sidecar"; then
-            echo "--> Problem with sidecar! Inspect the logs to diagnose the issue. <--"
-        fi
-    else
-        retry docker compose -f sidecar.compose.yaml pull -q
-        retry docker compose -f sidecar.compose.yaml up -d
+    SIDECAR_IMAGE=${container_registry}/cyral-sidecar:$SIDECAR_VERSION
+    retry docker pull -q $SIDECAR_IMAGE
+    retry docker run -d --name sidecar --network=host --log-driver=local --log-opt max-size=500m --restart=unless-stopped --env-file .env $SIDECAR_IMAGE
+    if ! containerCheck "sidecar"; then
+        echo "--> Problem with sidecar! Inspect the logs to diagnose the issue. <--"
     fi
 }
