Add error handling

diff --git a/files/cloud-init-functions.sh.tmpl b/files/cloud-init-functions.sh.tmpl
--- a/files/cloud-init-functions.sh.tmpl
+++ b/files/cloud-init-functions.sh.tmpl
@@ -149,6 +149,10 @@ function get_sidecar_version () {
     fi
     local access_token=$(echo "$token" | jq -r .access_token)
     local resp=$(${curl} --no-progress-meter --fail-with-body --request GET "https://${ControlPlane}/v2/sidecars/${SidecarId}" -H "Authorization: Bearer $access_token")
+    if [[ $? -ne 0 ]]; then
+        echo "Cannot determine sidecar version."
+        return 1
+    fi
     SIDECAR_VERSION=$(echo "$resp" | jq -r .sidecar.version)
 }
 
diff --git a/files/cloud-init-pre.sh.tmpl b/files/cloud-init-pre.sh.tmpl
--- a/files/cloud-init-pre.sh.tmpl
+++ b/files/cloud-init-pre.sh.tmpl
@@ -7,6 +7,10 @@ if [ -z "${sidecar_version}"] then
   echo "Sidecar version is unset - version will be dynamically managed."
   IS_DYNAMIC_VERSION="true"
   get_sidecar_version
+  if [ $? -ne 0 ]; then
+    echo "Error getting sidecar version from Control Plane. Dynamic version support is only enabled for Control Planes >= v4.10"
+    exit 1
+  fi
 fi
 
 echo "Sidecar version: ${SIDECAR_VERSION}"
