ENG-12120: Add custom EC2 health check script (#83)
* Add custom EC2 health check script

* Add autoscaling:SetInstanceHealth permission

* Fetch instance ID once

* Update README

diff --git a/files/cloud-init-pre.sh.tmpl b/files/cloud-init-pre.sh.tmpl
--- a/files/cloud-init-pre.sh.tmpl
+++ b/files/cloud-init-pre.sh.tmpl
@@ -2,6 +2,7 @@ mkdir -p /home/ec2-user/cyral/
 
 package_install
 get_secret
+fetch_hostname
 
 # Get the latest sidecar version from the Control Plane if necessary.
 IS_DYNAMIC_VERSION="false"
@@ -18,6 +19,46 @@ if [ -z $SIDECAR_VERSION ]; then
     echo "Sidecar version is undefined."
     exit 1
   fi
+
+  # Create custom health check scripts
+  cat << EOF > /home/ec2-user/cyral/healthcheck.sh
+#!/usr/bin/env bash
+health=\$(${curl} -sf -X GET "http://localhost:9000/health")
+if [ \$? -ne 0 ]; then
+  echo "Error getting sidecar health"
+  exit 1
+fi
+recycle_status=\$(echo \$health | jq -r .components.recycle.status)
+if [ \$recycle_status == "degraded" ]; then
+  echo "Sidecar instance has been marked for recycling - setting EC2 health to 'Unhealthy'"
+  aws autoscaling set-instance-health --region ${aws_region} --instance-id \$INSTANCE_ID --no-should-respect-grace-period --health-status Unhealthy
+fi
+EOF
+
+  cat << EOF > /etc/systemd/system/healthcheck.service
+[Unit]
+Description=Sidecar recycle EC2 health check
+[Service]
+Environment="INSTANCE_ID=$INSTANCE_ID"
+ExecStart=/home/ec2-user/cyral/healthcheck.sh
+EOF
+
+  cat << EOF > /etc/systemd/system/healthcheck.timer
+[Unit]
+Description=Sidecar recycle EC2 health check every 30 sec
+[Timer]
+OnBootSec=30
+OnUnitActiveSec=${recycle_health_check_interval_sec}
+AccuracySec=1
+[Install]
+WantedBy=timers.target
+EOF
+
+  # Start health check timer
+  chmod +x /home/ec2-user/cyral/healthcheck.sh
+  sudo systemctl enable healthcheck.timer
+  sudo systemctl daemon-reload
+  sudo systemctl start healthcheck.timer
 fi
 
 echo "Sidecar version: $SIDECAR_VERSION"
@@ -28,7 +69,6 @@ if [[ ${use_single_container} == "true" ]]; then
 else
     docker_compose_install
 fi
-fetch_hostname
 update_nginx_resolver
 load_certs
 load_idp_certs
