ENG-12832: Making load_certs echo Warning (#90)
* ENG-12832: Making load_certs echo Warning if certificate secrets not found

* Update files/cloud-init-functions.sh.tmpl

Co-authored-by: Justin Rich <2077508+jrich523@users.noreply.github.com>

* Update files/cloud-init-functions.sh.tmpl

Co-authored-by: Justin Rich <2077508+jrich523@users.noreply.github.com>

---------

Co-authored-by: Justin Rich <2077508+jrich523@users.noreply.github.com>

diff --git a/files/cloud-init-functions.sh.tmpl b/files/cloud-init-functions.sh.tmpl
--- a/files/cloud-init-functions.sh.tmpl
+++ b/files/cloud-init-functions.sh.tmpl
@@ -96,12 +96,12 @@ function get_secret(){
 function load_certs() {
     echo "Loading certificates..."
     local sidecar_tls_cert_secret_value sidecar_ca_cert_secret_value
-    sidecar_tls_cert_secret_value=$(
-        get_secret_value "${sidecar_tls_certificate_secret_arn}" "${sidecar_tls_certificate_role_arn}"
-    )
-    sidecar_ca_cert_secret_value=$(
-        get_secret_value "${sidecar_ca_certificate_secret_arn}" "${sidecar_ca_certificate_role_arn}"
-    )
+    if ! sidecar_tls_cert_secret_value=$(get_secret_value "${sidecar_tls_certificate_secret_arn}" "${SidecarTLSCertificateRoleArn}"); then
+        echo "WARNING: Unable to fetch shared TLS certificate from ${sidecar_tls_certificate_secret_arn} see error above"
+    fi
+    if ! sidecar_ca_cert_secret_value=$(get_secret_value "${sidecar_ca_certificate_secret_arn}" "${SidecarCACertificateRoleArn}"); then
+        echo "WARNING: Unable to fetch shared CA certificate from ${sidecar_ca_certificate_secret_arn}" see error above.
+    fi
     SIDECAR_TLS_KEY=$(echo "$sidecar_tls_cert_secret_value" | extract_key_from_json_input)
     SIDECAR_TLS_CERT=$(echo "$sidecar_tls_cert_secret_value" | extract_cert_from_json_input)
     SIDECAR_CA_KEY=$(echo "$sidecar_ca_cert_secret_value" | extract_key_from_json_input)
