ENG-12118/ENG-12121: Enable instance recycle and dynamically manage sidecar version (#82)
* Enable instance recycle and dynamically manage sidecar version

* Add error handling

* Missing semicolon

diff --git a/files/cloud-init-functions.sh.tmpl b/files/cloud-init-functions.sh.tmpl
--- a/files/cloud-init-functions.sh.tmpl
+++ b/files/cloud-init-functions.sh.tmpl
@@ -134,6 +134,28 @@ function get_token () {
     token_error=$(echo $?)
 }
 
+function get_sidecar_version () {
+    echo "Getting sidecar version from Control Plane..."
+    get_token "443"
+    if [[ $token_error -ne 0 ]]; then
+        error_443="$token"
+        get_token "8000"
+        if [[ $token_error -ne 0 ]]; then
+            echo "Unable to retrieve token!!"
+            echo "Attempt on 443: $error_443"
+            echo "Attempt on 8000: $token"
+            return 1
+        fi
+    fi
+    local access_token=$(echo "$token" | jq -r .access_token)
+    local resp=$(${curl} --no-progress-meter --fail-with-body --request GET "https://${controlplane_host}/v2/sidecars/${sidecar_id}" -H "Authorization: Bearer $access_token")
+    if [[ $? -ne 0 ]]; then
+        echo "Error retrieving sidecar version from Control Plane."
+        return 1
+    fi
+    SIDECAR_VERSION=$(echo "$resp" | jq -r '.sidecar.version // empty')
+}
+
 function download_sidecar () {
     local access_token url
     echo "Downloading Sidecar Compose File..."
@@ -144,15 +166,15 @@ function download_sidecar () {
         if [[ $token_error -ne 0 ]]; then
             echo "Unable to retrieve token!!"
             echo "Attempt on 443: $error_443"
-            echo "Attempt on 8000: $token"        
+            echo "Attempt on 8000: $token"
             return 1
         fi
     fi
     access_token=$(echo "$token" | jq -r .access_token)
-    url="https://${controlplane_host}/deploy/docker-compose?TemplateVersion=${sidecar_version}&TemplateType=terraform&LogIntegration=${log_integration}&MetricsIntegration=${metrics_integration}&HCVaultIntegrationID=${hc_vault_integration_id}&WiresEnabled=${repositories_supported}"
+    url="https://${controlplane_host}/deploy/docker-compose?TemplateType=terraform&LogIntegration=${log_integration}&MetricsIntegration=${metrics_integration}&HCVaultIntegrationID=${hc_vault_integration_id}&WiresEnabled=${repositories_supported}&TemplateVersion=$SIDECAR_VERSION"
     echo "Trying to download the sidecar template from: $url"
     if ! ${curl} -fsS --no-progress-meter -o /home/ec2-user/sidecar.compose.yaml -L "$url" -H "Authorization: Bearer $access_token"; then
-        echo "Unable to download compose file for version ${sidecar_version}, please make sure all parameters are correct"
+        echo "Unable to download compose file for version $SIDECAR_VERSION, please make sure all parameters are correct"
         return 1
     fi
     return 0
diff --git a/files/cloud-init-pre.sh.tmpl b/files/cloud-init-pre.sh.tmpl
--- a/files/cloud-init-pre.sh.tmpl
+++ b/files/cloud-init-pre.sh.tmpl
@@ -1,6 +1,27 @@
-
 mkdir -p /home/ec2-user/cyral/
+
 package_install
+get_secret
+
+# Get the latest sidecar version from the Control Plane if necessary.
+IS_DYNAMIC_VERSION="false"
+SIDECAR_VERSION=${sidecar_version}
+if [ -z $SIDECAR_VERSION ]; then
+  echo "Sidecar version is unset - version will be dynamically managed."
+  IS_DYNAMIC_VERSION="true"
+  get_sidecar_version
+  if [ $? -ne 0 ]; then
+    echo "Error getting sidecar version from Control Plane. Dynamic version support is only enabled for Control Planes >= v4.10"
+    exit 1
+  fi
+  if [ -z $SIDECAR_VERSION ]; then
+    echo "Sidecar version is undefined."
+    exit 1
+  fi
+fi
+
+echo "Sidecar version: $SIDECAR_VERSION"
+
 docker_setup
 if [[ ${use_single_container} == "true" ]]; then
     echo "Skipping Docker Compose Install, not required for single container"
@@ -9,7 +30,6 @@ else
 fi
 fetch_hostname
 update_nginx_resolver
-get_secret
 load_certs
 load_idp_certs
 registry_login
@@ -22,7 +42,9 @@ fi
 echo "Initializing environment variables..."
 cat > /home/ec2-user/.env << EOF
 SIDECAR_ID=${sidecar_id}
-SIDECAR_VERSION=${sidecar_version}
+SIDECAR_VERSION=$SIDECAR_VERSION
+IS_DYNAMIC_VERSION=$IS_DYNAMIC_VERSION
+IS_RECYCLABLE=true
 CONTROLPLANE_HOST=${controlplane_host}
 CONTAINER_REGISTRY=${container_registry}
 SECRETS_LOCATION=${secrets_location}
